### ISSUE TITLE
Update Travis and Codcov settings using nbogojevic account

### ISSUE THREAD

**Issue by roufa85** [nbogojevic/kafka-operator#14]
Hello @nbogojevic!

We have set up Travis build as well as Codcov for code coverage using our personal accounts.

In order to reflect the current build status and code coverage for this main working stream repository, the same settings should be done by creating two accounts and connecting them the repository nbogojevic/kafka-operator.

Here are the steps to get an up-to-date build status (which would take up to 5 min):

1. Create a Travis account and connect it to the repo
2. Create a codecov.io account and connect it to the repo
3. Update the status badges in the README.md

Cheers,

Raouf..

**Comment by nbogojevic** [comment]
CI put in place and working.
